# Why Use NumPy?

### Benefits of using NumPy:

**1. Speed**

**2. Multidimensional array data structures**

**3. Optimized built-in mathematical functions**

In [29]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100_000_000)

# Case 1
start = time.time()
sum(x) / len(x)
print("Case 1:", time.time() - start)

# Case 2
start = time.time()
np.mean(x)
print("Case 2:", time.time() - start)

Case 1: 6.318641424179077
Case 2: 0.06072711944580078


In [32]:
print(f"{round(6.319 / 0.061, 1)}x faster!")

103.6x faster!


# Creating and Saving NumPy ndarrays

In [33]:
# Create a 1D array that contains only integers
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

### `numpy.ndarray.ndim`

**Rank of an Array** - number of dimensions it has

Syntax: `ndarray.ndim`

Returns the number of array dimensions.

In [35]:
# 1-D array
x = np.array([1, 2, 3])
x.ndim

1

In [40]:
# 2-D array
y = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
y.ndim

2

In [43]:
# 3-D array
z = np.ones((2, 3, 4))
z.ndim

3

In general *N*-Dimensional arrays have rank *N*.

### `numpy.ndarray.shape`

Syntax: `ndarray.shape`

Returns a tuple representing the array dimensions.

In [46]:
x.shape

(3,)

In [44]:
y.shape

(3, 3)

In [45]:
z.shape

(2, 3, 4)

### `numpy.ndarray.dtype`

Syntax: `ndarray.dtype`

Returns the data-type of the elements.

#### Using a 1-D Array of Integers

In [52]:
# Create a 1D array that contains only integers
x = np.array([56, 12, 89, 2, 71])

# Print information about x
print('x =', x)
print('x has dimensions:', x.ndim)
print('x is an object of type:', type(x))
print('The elements of in x are of type:', x.dtype)

x = [56 12 89  2 71]
x has dimensions: 1
x is an object of type: <class 'numpy.ndarray'>
The elements of in x are of type: int64


*`.dtype` attribute tells that the elements of x are stored in memory as **signed 64-bit integers**.*

#### Using 1-D Array of Strings

In [58]:
# Create a rank 1 ndarray that only contains strings
y = np.array(['hello', 'world'])

# Print information about y
print('x =', y)
print('x has dimensions:', y.ndim)
print('x is an object of type:', type(y))
print('The elements of in x are of type:', y.dtype)

x = ['hello' 'world']
x has dimensions: 1
x is an object of type: <class 'numpy.ndarray'>
The elements of in x are of type: <U5


*`.dtype` attribute tells that the elements of x are stored in memory as **Unicode strings of 5 characters**.*

#### Using a 1-D Array of Mixed Datatype

In [60]:
# Create a rank 1 ndarray from a Python list that contains integers and strings
z = np.array([10, 99, "HELLO"])

# Print information about z
print('x =', z)
print('x has dimensions:', z.ndim)
print('x is an object of type:', type(z))
print('The elements of in x are of type:', z.dtype)

x = ['10' '99' 'HELLO']
x has dimensions: 1
x is an object of type: <class 'numpy.ndarray'>
The elements of in x are of type: <U21


*We can see that even though the Python list had mixed data types, the elements in x are all of the same type, namely, **Unicode strings of 21 characters**.*

#### Using a 1-D Array of Int and Float

In [61]:
# Create a rank 1 ndarray that contains integers
x = np.array([10, 20, 30])

# Create a rank 1 ndarray that contains floats
y = np.array([10.0, 20.0, 30.0])

# Create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 3])

# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


#### Using a 1-D Array of Float, and specifying the datatype of each element as int64

In [63]:
# Create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# Print the dtype x
print('x =', x)
print('The elements in x are of type:', x.dtype)

x = [1 2 3 4 5]
The elements in x are of type: int64


### `numpy.ndarray.size`

Syntax: `ndarray.size`

Returns a total elements in array.

In [73]:
# Create a rank 2 ndarray that only contains integers
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print('A =\n', A)

# Print information about A
print('A has dimensions:', A.shape)
print('A has a total of', A.size, 'elements')
print('A is an object of type:', type(A))
print('The elements in A are of type:', A.dtype)

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A has dimensions: (3, 3)
A has a total of 9 elements
A is an object of type: <class 'numpy.ndarray'>
The elements in A are of type: int64


### Save the NumPy array to a File

In [84]:
# Create 1D array
arr1 = np.array([9, 7, 5, 3, 1])

# Save arr1 into the current directory
np.save("my_array", arr1)

In [85]:
ls

NumPy-1.ipynb*  NumPy-2.ipynb*  my_array.npy*


In [90]:
# Load the saved array from current directory into variable a1
a1 = np.load("my_array.npy")

print("a1 =", a1)
print("a1 is an object of type:", type(a1))
print("The elements in a1 are of type:", a1.dtype)

a1 = [9 7 5 3 1]
a1 is an object of type: <class 'numpy.ndarray'>
The elements in a1 are of type: int64
