# Using Built-in Functions to Create ndarrays

## Create a Numpy array of zeros with a desired shape

In [1]:
import numpy as np

In [2]:
# Create 3 x 4 ndarray full of zeros
X = np.zeros((3, 4))
print(X, end='\n\n')

# Print information about X
print("X has dimensions:", X.shape)
print("X is an object of type:", type(X))
print("The elements in X are of type:", X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


## Create a Numpy array of ones

In [5]:
# Create a 3 x 2 ndarray full of ones
Y = np.ones((3, 2))
print(Y, end="\n\n")

# Print information about Y
print("Y has dimensions:", Y.shape)
print("Y is an object of type:", type(Y))
print("The elements in Y are of type:", Y.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

Y has dimensions: (3, 2)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: float64


## Create a Numpy array of constants

In [16]:
# Create a 2 x 3 ndarray full of fives. 
Z = np.full((2, 3), 5)
Z

array([[5, 5, 5],
       [5, 5, 5]])

## Create a Numpy array of an Identity matrix

In [10]:
# Create a 5 x 5 Identity matrix
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Create a Numpy array - diagonal matrix that is a square matrix of constants

In [12]:
# Create a 4 x 4 diagonal matrix that contains the numbers on its main diagonal
B = np.diag([10, 20, 30, 40, 50])
B

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

## `numpy.arange`

Syntax: `numpy.arange([`**`start`**`, ]`**`stop`**`, [`**`step`**`, ] dtype =`**`None`**`)`

Returns evenly spaced values within a given interval.

In [24]:
# Create a rank 1 ndarray that has sequential integers from 0 to 9
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Create a rank 1 ndarray that has sequential integers from 4 to 9
arr2 = np.arange(4, 10)
arr2

array([4, 5, 6, 7, 8, 9])

In [26]:
# Create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3
arr3 = np.arange(1, 14, 3)
arr3

array([ 1,  4,  7, 10, 13])

## `numpy.linspace`

Syntax: `numpy.linspace(`**`start`**`, `**`stop`**`, `**`num`**`= 50, endpoint=True, retstep=False, dtype =`**`None`**`, axis=0)`

Returns evenly spaced numbers over a specified interval.

In [32]:
# Create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25
arr4 = np.linspace(0, 25, 10)
arr4

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [17]:
# Create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25, with 25 excluded
arr5 = np.linspace(0, 25, 10, endpoint = False)
arr5

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

## `numpy.reshape` function

Syntax: `numpy.reshape(`*`array, newshape, order='C')`*

Gives a new shape to an array without changing its data.

In [31]:
# Create a rank 1 ndarray with sequential integers from 0 to 19
arr6 = np.arange(20)
print("Original array =", arr6)

# Reshape x into a 4 x 5 ndarray
arr6 = np.reshape(arr6, (4, 5))
print("\nReshaped array =\n", arr6)
print("Array dimensions:", arr6.ndim)
print(type(arr6))
print(arr6.dtype)

Original array = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped array =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Array dimensions: 2
<class 'numpy.ndarray'>
int64


## `numpy.ndarray.reshape` - method

Syntax: `ndarray.reshape(`*`shape, order='C'`*`)`

Returns an array containing the same data with a new shape.

In [35]:
# Create a rank 1 ndarray with sequential integers from 0 to 19 and reshape it to a 4 x 5 array
arr7 = np.arange(20).reshape(4, 5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
# Create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50, with 50 excluded.
# Then reshape it to a 5 x 2 ndarray
arr8 = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
arr8

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [51]:
# Create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
np.random.random((3, 3))

array([[0.64958347, 0.18311799, 0.21742578],
       [0.22424889, 0.06453682, 0.5879279 ],
       [0.71515848, 0.60596226, 0.88633399]])

In [93]:
# Create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
np.random.randint(4, 15, size=(3, 2))

array([[ 7,  9],
       [ 5,  9],
       [10, 14]])

**`np.random.normal(mean, standard deviation, size=shape)`**

Creates an ndarray with the given `shape` that contains random numbers picked from a `normal` (Gaussian) distribution with the given `mean` and `standard deviation`.

In [92]:
# Create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
np.random.normal(0, 0.1, size=(1000, 1000))

array([[ 0.07964942, -0.07805102, -0.05051442, ..., -0.13233207,
         0.06251273, -0.02002545],
       [ 0.03863298, -0.02022208,  0.13141425, ..., -0.1505074 ,
         0.04177118, -0.15713625],
       [ 0.1417936 , -0.02894599,  0.07271848, ..., -0.12651055,
        -0.08148068, -0.09627197],
       ...,
       [-0.01000852,  0.12098828, -0.1556035 , ...,  0.0417002 ,
         0.04867479,  0.05644798],
       [ 0.02237573,  0.17180022,  0.11208925, ...,  0.1028789 ,
         0.00916841, -0.07782261],
       [-0.07789784, -0.06517056, -0.05564137, ...,  0.07028896,
        -0.15974858,  0.00230265]])