# Accessing, Deleting, and Inserting Elements Into ndarrays

### Access individual elements of 1-D array

In [1]:
import numpy as np

In [8]:
# Create a rank 1 ndarray that contains integers from 1 to 5
x = np.arange(1, 6)
print('x =', x)
print()
# Let's access some elements with positive indices
print("The first element in x:", x[0])
print("The second element in x:", x[1])
print("The fifth (last) element in x:", x[4])
print()
# Let's access the same elements with negative indices
print("The first element in x:", x[-5])
print("The second element in x:", x[-4])
print("The fifth (last) element in x:", x[-1])

x = [1 2 3 4 5]

The first element in x: 1
The second element in x: 2
The fifth (last) element in x: 5

The first element in x: 1
The second element in x: 2
The fifth (last) element in x: 5


### Modify an element of 1-D array

In [11]:
# Create a rank 1 ndarray that contains integers from 1 to 5
x = np.arange(1, 6)
print('Original:\n x =', x)
print()
# Change the fourth element in x from 4 to 20
x[3] = 20

print('Modified:\n x =', x)

Original:
 x = [1 2 3 4 5]

Modified:
 x = [ 1  2  3 20  5]


### Access individual elements of 2-D array

To access elements in rank 2 ndarrays we need to provide 2 indices in the form `[row, column]`

In [20]:
# Create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.arange(1, 10).reshape(3, 3)
print('X =\n', X)
print()

# Let's access some elements in X
print('This is (0,0) Element in X:', X[0, 0])
print('This is (0,1) Element in X:', X[0, 1])
print('This is (2,2) Element in X:', X[2, 2])

X =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


### Modify an element of 2-D array

In [29]:
# Create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X = np.arange(1, 10).reshape(3, 3)
print('Original:\nX =\n', X)
print()
# Change the (0,0) element in X from 1 to 20
X[0, 0] = 20

print('Modified:\nX =\n', X)

Original:
X =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified:
X =
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## `numpy.delete` function

Syntax: `numpy.delete(ndarray, elements, axis)`

This function `deletes` the given list of `elements` from the given `ndarray` along the specified `axis`.

In [42]:
# Create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# Create a rank 2 ndarray
Y = np.arange(1, 10).reshape(3, 3)

print('Original x =', x)
# delete the first and last element of x
x = np.delete(x, [0, 4])
print('Modified x = ', x)

print('\nOriginal Y = \n', Y)
# delete the first row of Y
w = np.delete(Y, [0], axis=0)

# delete the first and last column of Y
v = np.delete(Y, [0, 2], axis=1)

print('\nw =\n', w)
print('\nv =\n', v)

Original x = [1 2 3 4 5]
Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w =
 [[4 5 6]
 [7 8 9]]

v =
 [[2]
 [5]
 [8]]


## numpy.append

Syntax: `numpy.append(array, values, axis=None)`

This function appends the given list of `elements` to `ndarray` along the specified `axis`.

### Append elements

In [60]:
# create a rank 1 ndarray
x = np.arange(1, 6)

# create a rank 2 ndarray
y = np.arange(1, 7).reshape(2, 3)


print('Original x =', x)
# append the integer 6 to x
x = np.append(x, 6)
print('x =', x)

# append the integer 7 and 8 to x
x = np.append(x, [7, 8])
print('x =', x)

print('\nOriginal y =\n', y)
# append a new row containing 7,8,9 to y
v = np.append(y, [[7, 8, 9]], axis=0)

# append a new column containing 9 and 10 to y
q = np.append(y, [[9], [10]], axis=1)

print('\nv =\n', v)
print('\nq =\n', q)

Original x = [1 2 3 4 5]
x = [1 2 3 4 5 6]
x = [1 2 3 4 5 6 7 8]

Original y =
 [[1 2 3]
 [4 5 6]]

v =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q =
 [[ 1  2  3  9]
 [ 4  5  6 10]]


## `numpy.insert`

Syntax: `numpy.insert(ndarray, index, elements, axis)`

This function inserts the given list of `elements` to `ndarray` right before the given `index` along the specified `axis`.

### Insert elements

In [80]:
# create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# create a rank 2 ndarray 
y = np.array([[1,2,3],
              [7,8,9]])

print('Original x =', x)

# insert the integer 3 and 4 between 2 and 5 in x
x = np.insert(x, 2, [3, 4])
print('x =', x)

print('\nOriginal y =\n', y)

# insert a row between the first and last row of y
w = np.insert(y, 1, [4, 5, 6], axis=0)

# insert a column full of 5s between the first and second column of y
v = np.insert(y, 1, [5], axis=1)

print('\nw =\n', w)
print('\nv =\n', v)

Original x = [1 2 5 6 7]
x = [1 2 3 4 5 6 7]

Original y =
 [[1 2 3]
 [7 8 9]]

w =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v =
 [[1 5 2 3]
 [7 5 8 9]]


## `numpy.hstack` and `numpy.vstack`

Syntax:

`numpy.hstack(`*`sequence_of_ndarray`*`)` - Returns a stacked array formed by stacking the given arrays in sequence horizontally (column-wise).

`numpy.vstack(`*`sequence_of_ndarray`*`)` - Returns a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise).

### Stack arrays

In [126]:
# create a rank 1 ndarray 
x = np.array([1, 2])

# create a rank 2 ndarray 
y = np.array([[3, 4],
              [5, 6]])

print('x =', x)
print('\ny =\n', y)

# stack x on top of y
z = np.vstack((x, y))

# stack x on the right of Y. We need to reshape x in order to stack it on the right of Y
w = np.hstack(( y, x.reshape(2, 1) ))

print('\nz =\n', z)
print('\nw =\n', w)

x = [1 2]

y =
 [[3 4]
 [5 6]]

z =
 [[1 2]
 [3 4]
 [5 6]]

w =
 [[3 4 1]
 [5 6 2]]
