# Slicing ndarrays

In [1]:
import numpy as np

### Slicing in a 2-D ndarray

In [35]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4, 5)
print('x =\n', x)

# select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
y = x[1:4, 2:5]
print('\ny =\n', y)

# select the same elements as above using method 2
w = x[1:, 2:]
print('\nw =\n', w)

# select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
z = x[:3, 2:4]
print('\nz =\n', z)

# select all the elements in the 3rd row
v = x[2, :]
print('\nv =\n', v)

# select all the elements in the 3rd column
q = x[:, 2]
print('\nq =\n', q)

# select all the elements in the 3rd column but return a rank 2 ndarray
r = x[:, [2]]
print('\nr =\n', r)

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

y =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

w =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

z =
 [[ 2  3]
 [ 7  8]
 [12 13]]

v =
 [10 11 12 13 14]

q =
 [ 2  7 12 17]

r =
 [[ 2]
 [ 7]
 [12]
 [17]]


### Slicing and editing elements in a 2-D ndarray

In [47]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4, 5)
print('x =\n', x)

# select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
y = x[1:4, 2:5]
print('\ny =\n', y)

# change the last element in y to 555
y[2, 2] = 555

print('\nx =\n', x)

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

y =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

x =
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


## `numpy.ndarray.copy`

Syntax: `ndarray.copy(`*`order='C'`*`)`

Returns a copy of the array.

In [11]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4, 5)
print('x =\n', x)

# create a copy of the slice using the np.copy() function
y = np.copy(x[1:4, 2:5])

#  create a copy of the slice using the copy as a method
z = x[1:4, 2:5].copy()

# change the last element in y to 555
y[2, 2] = 555

# change the last element in z to 444
z[2, 2] = 444

print('\ny =\n', y)
print('\nz =\n', z)
print('\nx =\n', x)

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

y =
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

z =
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Use an array as indices to either make slices, select, or change elements

In [25]:
# create a 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4, 5)

# create a rank 1 ndarray that will serve as indices to select elements from x
indices = np.array([1, 3])

print('x =\n', x)
print('\nindicies =', indices)

# use the indices ndarray to select the 2nd and 4th row of X
y = x[indices,:]

# use the indices ndarray to select the 2nd and 4th column of X
z = x[:, indices]

print('\ny =\n', y)
print('\nz =\n', z)

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indicies = [1 3]

y =
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

z =
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


### Use an array as indices to extract specific rows from a rank 2 ndarray

In [32]:
# Let's create a rank 2 ndarray
x = np.random.randint(1, 20, size=(50, 5))
print("Shape of x is: ", x.shape)

Shape of x is:  (50, 5)


In [43]:
# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(x)` (50)
# The row_indices would represent the indices of rows of x
row_indices = np.random.randint(0, 50, size=10)
print("Random 10 indices:", row_indices)

Random 10 indices: [ 4 49  0 44 37  2 11  0  1 17]


In [46]:
# Print those rows of x whose indices are represented by entire row_indices ndarray
x_subset = x[row_indices, :]
print(x_subset)
print()
x_subset = x[row_indices[4:8], :]
print(x_subset)

[[ 8  4  5 13  9]
 [ 9  1 14  6 11]
 [14  6  9  9 18]
 [ 7  8 16 12 13]
 [ 7 10 10  8 14]
 [18  4 11  5 17]
 [15 18 19 13 10]
 [14  6  9  9 18]
 [ 6  3  8  8 13]
 [16  7  2 19  8]]

[[ 7 10 10  8 14]
 [18  4 11  5 17]
 [15 18 19 13 10]
 [14  6  9  9 18]]


## `numpy.diag`

Syntax: `numpy.diag(array, k=0)`

Extracts or constructs the diagonal elements.

In [62]:
# create a 5 x 5 ndarray that contains integers from 1 to 26
x = np.arange(1, 26).reshape(5, 5)
print('x =\n', x)

print('\nw =\n', np.diag(x))

print('\ny =\n', np.diag(x, k=1))

print('\nz =\n', np.diag(x, k=-1))

x =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

w =
 [ 1  7 13 19 25]

y =
 [ 2  8 14 20]

z =
 [ 6 12 18 24]


## `numpy.unique`

Syntax: `numpy.unique(`*`array, return_index=False, return_inverse=False, return_counts=False, axis=None`*`)`

Returns the sorted unique elements of an array.

In [67]:
x = np.array([[1, 2, 3],
               [8, 5, 2],
               [2, 1, 3]])

print("The unique elements in x:", np.unique(x))

The unique elements in x: [1 2 3 5 8]
