# Boolean Indexing, Set Operations, and Sorting

In [1]:
import numpy as np

### Boolean indexing

In [11]:
# create a 5 x 5 ndarray that contains integers from 0 to 24
x = np.arange(25).reshape(5, 5)
print('x =\n', x)

print("\nThe elements in X that are greater than 10:", x[x > 10])
print("The elements in X that less than or equal to 7:", x[x <= 7])
print("The elements in X that are between 10 and 17:", x[(x > 10) & (x < 17)])

x =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


### Set operations

In [21]:
# create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 7, 8])
print('x =', x)
print('y =', y)

# use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x, y))
print('The elements that are in x that are not in y:', np.setdiff1d(x, y))
print('All the elements of x and y:', np.union1d(x, y))

x = [1 2 3 4 5]
y = [2 4 6 7 8]
The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


## `numpy.ndarray.sort` method

Syntax: `ndarray.sort(`*`axis=-1, kind=None, order=None`*`)`

Sort an array in-place.

### Sort arrays using sort() function

In [80]:
x = np.random.randint(0, 10, 10)
print('Array:\n', x)
print('\nSorted x (out of place):\n', np.sort(x))

Array:
 [6 4 6 3 5 3 2 5 7 0]

Sorted x (out of place):
 [0 2 3 3 4 5 5 6 6 7]


In [81]:
# Returns the sorted unique elements of an array
print(np.unique(x))

[0 2 3 4 5 6 7]


### Sort rank-1 arrays using sort() method

In [89]:
y = np.random.randint(10, 101, size=11)
print('y =', y)

y.sort()
print('\ny after sorting:', y)

y = [44 67 75 74 37 10 56 80 38 78 30]

y after sorting: [10 30 37 38 44 56 67 74 75 78 80]


## `numpy.sort` function

Syntax: `numpy.sort(`*`array, axis=-1, kind=None, order=None`*`)`

Return a sorted copy of an array.

> ***Tip:*** *You can read axis = 0 as "**down**" and axis = 1 as "**across**" the given 2-D array, to have a correct usage of axis in your methods/functions.*

### Sort rank-2 arrays by specific axis

In [99]:
# create an unsorted rank 2 ndarray
Z = np.random.randint(150, size=(3, 3))
print('Original Z =\n', Z)
print('\nZ with sorted columns :\n', np.sort(Z, axis=0))
print('\nZ with sorted rows :\n', np.sort(Z, axis=1))

Original Z =
 [[ 79  91  99]
 [101  13 113]
 [100  94  72]]

Z with sorted columns :
 [[ 79  13  72]
 [100  91  99]
 [101  94 113]]

Z with sorted rows :
 [[ 79  91  99]
 [ 13 101 113]
 [ 72  94 100]]
