#  Arithmetic operations and Broadcasting

In [1]:
import numpy as np

### Element-wise arithmetic operations on 1-D arrays

In [14]:
# create two rank 1 ndarrays
x = np.array([1, 4, 7, 10])
y = np.array([3.5, 5.5, 7.5, 9.5])
print('x =', x)
print('y =', y)

# perfrom basic element-wise operations using arithmetic symbols and functions

# Addition
print("\nx + y =", x + y)
print("add(x, y) =", np.add(x, y))

# Subtraction
print("\nx - y =", x - y)
print("subtract(x, y) =", np.subtract(x, y))

# Multiplication
print("\nx * y =", x * y)
print("multiply(x, y) =", np.multiply(x, y))

# Division
print("\nx / y =", x / y)
print("divide(x, y) =", np.divide(x, y))

x = [ 1  4  7 10]
y = [3.5 5.5 7.5 9.5]

x + y = [ 4.5  9.5 14.5 19.5]
add(x, y) = [ 4.5  9.5 14.5 19.5]

x - y = [-2.5 -1.5 -0.5  0.5]
subtract(x, y) = [-2.5 -1.5 -0.5  0.5]

x * y = [ 3.5 22.  52.5 95. ]
multiply(x, y) = [ 3.5 22.  52.5 95. ]

x / y = [0.28571429 0.72727273 0.93333333 1.05263158]
divide(x, y) = [0.28571429 0.72727273 0.93333333 1.05263158]


### Element-wise arithmetic operations on a 2-D array (Same shape)

In [19]:
# create two rank 1 ndarrays
X = np.array([1, 4, 7, 10]).reshape(2, 2)
Y = np.array([3.5, 5.5, 7.5, 9.5]).reshape(2, 2)
print('X =\n', X)
print('\nY =\n', Y)

# perfrom basic element-wise operations using arithmetic symbols and functions

# Addition
print("\nX + Y =\n", X + Y)
print("\nadd(X, Y) =\n", np.add(X, Y))

# Subtraction
print("\nX - Y =\n", X - Y)
print("\nsubtract(X, Y) =\n", np.subtract(X, Y))

# Multiplication
print("\nX * Y =\n", X * Y)
print("\nmultiplY(X, Y) =\n", np.multiply(X, Y))

# Division
print("\nX / Y =\n", X / Y)
print("\ndivide(X, Y) =\n", np.divide(X, Y))

X =
 [[ 1  4]
 [ 7 10]]

Y =
 [[3.5 5.5]
 [7.5 9.5]]

X + Y =
 [[ 4.5  9.5]
 [14.5 19.5]]

add(X, Y) =
 [[ 4.5  9.5]
 [14.5 19.5]]

X - Y =
 [[-2.5 -1.5]
 [-0.5  0.5]]

subtract(X, Y) =
 [[-2.5 -1.5]
 [-0.5  0.5]]

X * Y =
 [[ 3.5 22. ]
 [52.5 95. ]]

multiplY(X, Y) =
 [[ 3.5 22. ]
 [52.5 95. ]]

X / Y =
 [[0.28571429 0.72727273]
 [0.93333333 1.05263158]]

divide(X, Y) =
 [[0.28571429 0.72727273]
 [0.93333333 1.05263158]]


### Additional mathematical functions

In [28]:
x = np.array([1, 2, 3, 4])
print("x =", x)

# apply different mathematical functions to all elements of x
print("\nEXP(x) =", np.exp(x))
print("\nSQRT(x) =", np.sqrt(x))
print("\nPOW(x, 2) =", np.power(x, 2))

x = [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x, 2) = [ 1  4  9 16]


### Statistical functions

In [19]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print('x =\n', x)

print("\nAverage of all elements in x: ", x.mean())
print("Average of all elements in the columns of x:", x.mean(axis=0))
print("Average of all elements in the rows of x:", x.mean(axis=1))

print("\nSum of all elements in x:", x.sum())
print("Sum of all elements in the columns of x:", x.sum(axis=0))
print("Sum of all elements in the rows of x:", x.sum(axis=1))

print("\nStandard Deviation of all elements in x:", x.std())
print("Standard Deviation of all elements in the columns of x:", x.std(axis=0))
print("Standard Deviation of all elements in the rows of x:", x.std(axis=1))

print("\nMedian of all elements in x:", np.median(x))
print("Median of all elements in the columns of x:", np.median(x, axis=0))
print("Median of all elements in the rows of x:", np.median(x, axis=1))

print("\nMaximum value of all elements in x:", x.max())
print("Maximum value of all elements in the columns of x:", x.max(axis=0))
print("Maximum value of all elements in the rows of x:", x.max(axis=1))

print("\nMinimum value of all elements in x:", x.min())
print("Minimum value of all elements in the columns of x:", x.min(axis=0))
print("Minimum value of all elements in the rows of x:", x.min(axis=1))

x =
 [[1 2]
 [3 4]]

Average of all elements in x:  2.5
Average of all elements in the columns of x: [2. 3.]
Average of all elements in the rows of x: [1.5 3.5]

Sum of all elements in x: 10
Sum of all elements in the columns of x: [4 6]
Sum of all elements in the rows of x: [3 7]

Standard Deviation of all elements in x: 1.118033988749895
Standard Deviation of all elements in the columns of x: [1. 1.]
Standard Deviation of all elements in the rows of x: [0.5 0.5]

Median of all elements in x: 2.5
Median of all elements in the columns of x: [2. 3.]
Median of all elements in the rows of x: [1.5 3.5]

Maximum value of all elements in x: 4
Maximum value of all elements in the columns of x: [3 4]
Maximum value of all elements in the rows of x: [2 4]

Minimum value of all elements in x: 1
Minimum value of all elements in the columns of x: [1 2]
Minimum value of all elements in the rows of x: [1 3]


### Change value of all elements of an array

In [29]:
print('X =\n', x)
print('\n3 * X =\n', 3 * x)
print('\n3 / X =\n', 3 / x)
print('\n3 + X =\n', 3 + x)
print('\n3 - X =\n', 3 - x)

X =
 [[1 2]
 [3 4]]

3 * X =
 [[ 3  6]
 [ 9 12]]

3 / X =
 [[3.   1.5 ]
 [1.   0.75]]

3 + X =
 [[4 5]
 [6 7]]

3 - X =
 [[ 2  1]
 [ 0 -1]]


### Arithmetic operations on 2-D arrays (Compatible shape)

In [47]:
# create a rank 1 ndarray
X = np.array([1, 2, 3])
# create a 3x1 ndarray
Y = np.array([1, 2, 3]).reshape(3, 1)
# create a 3x3 array
Z = np.arange(1, 10).reshape(3, 3)

print('X =\n', X)
print('\nY =\n', Y)
print('\nZ =\n', Z)

print('\nX + Y =\n', X + Y)
print('\nX + Z =\n', X + Z)
print('\nY + Z =\n', Y + Z)

X =
 [1 2 3]

Y =
 [[1]
 [2]
 [3]]

Z =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

X + Y =
 [[2 3 4]
 [3 4 5]
 [4 5 6]]

X + Z =
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Y + Z =
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
